name: "Build and test"
on:
  pull_request:
  push:
jobs:
  cargo-build:
    runs-on: Linux
    strategy:
      fail-fast: false
      matrix:
        target: 
          - "x86_64-pc-windows-gnu"
          - "x86_64-unknown-linux-gnu"
        toolchain:
          - "stable"
        flags:
          - ""
          - "--release"
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          rustup target add ${{ matrix.target }}
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev cmake libshaderc-dev libvulkan-dev glslc
          sudo apt-get install -y libclang-dev cmake
      - run: cargo build --verbose ${{ matrix.flags }}
        working-directory: ./nobodywho

  cargo-test:
    runs-on: Linux
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup update stable && rustup default stable
          rustup target add x86_64-unknown-linux-gnu
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev cmake libshaderc-dev libvulkan-dev glslc

      - run: wget "https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q5_K_M.gguf" -O ./nobodywho/model.bin
      - run: cargo test -- --nocapture --test-threads=1
        working-directory: ./nobodywho
