name: "Build and test"
on:
  pull_request:
  push:
jobs:
  cargo-build-linux:
    runs-on: Linux
    strategy:
      fail-fast: false
      matrix:
        target:
          - "x86_64-unknown-linux-gnu"
        profile:
          - "debug"
          - "release"
    steps:
      - uses: actions/checkout@v4

      - name: "Setup rust toolchain"
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup update stable
          rustup default stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: "Install distro dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev cmake libshaderc-dev libvulkan-dev glslc
          sudo apt-get install -y libclang-dev cmake

      - name: "Compile for linux"
        run: cargo build --verbose ${{ matrix.profile == 'release' && '--release' || '' }}
        working-directory: ./nobodywho

      - name: "Rename built file"
        run: cp ./nobodywho/target/${{ matrix.profile }}/libnobodywho.so ./nobodywho-${{ matrix.target }}-${{ matrix.profile }}.so

      - name: "Upload build artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ matrix.profile }}
          path: ./nobodywho/target/${{ matrix.profile }}/libnobodywho.so


  cargo-build-windows:
    runs-on: Linux
    strategy:
      fail-fast: false
      matrix:
        target: 
          - "x86_64-pc-windows-gnu"
        profile:
          - "debug"
          - "release"
    steps:
      - uses: actions/checkout@v4

      - name: "Set up rust toolchain"
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup update stable
          rustup default stable
          rustup target add ${{ matrix.target }}
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: "Install deps from distro"
        run: |
          apt-get update
          apt-get install -y libclang-dev cmake mingw-w64

      - name: "Compile for windows"
        # HACK: C_INCLUDE_PATH specified manually here, because it can't find stdbool.h otherwise
        run: C_INCLUDE_PATH=/usr/lib/gcc/x86_64-w64-mingw32/13-win32/include cargo build --verbose --target ${{ matrix.target }} ${{ matrix.profile == 'release' && '--release' || '' }}
        working-directory: ./nobodywho

      - name: "Rename built file"
        run: cp ./nobodywho/target/${{ matrix.target }}/${{ matrix.profile }}/nobodywho.dll ./nobodywho-${{ matrix.target }}-${{ matrix.profile }}.dll
      
      - name: "Upload build artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ matrix.profile }}
          path: ./nobodywho-${{ matrix.target }}-${{ matrix.profile }}.dll


  cargo-build-macos:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        target: 
          - "x86_64-apple-darwin"
          - "aarch64-apple-darwin"
        profile:
          - "debug"
          - "release"
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup update stable
          rustup default stable
          rustup target add ${{ matrix.target }}
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - run: cargo build --verbose ${{ matrix.profile == 'release' && '--release' || '' }}
        working-directory: ./nobodywho

      - name: "Rename built file"
        run: cp ./nobodywho/target/${{ matrix.profile }}/libnobodywho.dylib ./nobodywho-${{ matrix.target }}-${{ matrix.profile }}.dylib

      - name: "Upload build artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ matrix.profile }}
          path: ./nobodywho-${{ matrix.target }}-${{ matrix.profile }}.dylib


  cargo-test:
    runs-on: Linux
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: "Set up rust toolchain"
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup update stable
          rustup default stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: "Install deps from distro"
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev cmake libshaderc-dev libvulkan-dev glslc

      - name: "Download test model"
        run: wget "https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q5_K_M.gguf" -O ./nobodywho/model.bin

      - name: "Run unit tests"
        run: cargo test -- --nocapture
        working-directory: ./nobodywho


  zip-distributable:
    needs: [cargo-build-linux, cargo-build-macos, cargo-build-windows]
    runs-on: Linux
    steps:
      - uses: actions/checkout@v4

      - name: "Download all build artifacts"
        uses: actions/download-artifact@v4
        with:
          path: ./nobodywho-release

      - name: Add gdextension file
        run: cp ./nobodywho/nobodywho.gdextension ./nobodywho-release

      - name: "Upload zipped build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: nobodywho-all-platforms
          path: ./nobodywho-release
