name: "Build and test"
on:
  pull_request:
  push:
jobs:
  cargo-build:
    runs-on: Linux
    strategy:
      fail-fast: false
      matrix:
        target: 
          - "x86_64-pc-windows-gnu"
          - "x86_64-unknown-linux-gnu"
        toolchain:
          - "stable"
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          rustup target add ${{ matrix.target }}
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
     - run: |
        sudo apt-get update
        sudo apt-get install -y libclang-dev
      - run: cargo build --verbose
        working-directory: ./nobody

  cargo-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: 
          - "x86_64-pc-windows-gnu"
          - "x86_64-unknown-linux-gnu"
        toolchain:
          - "stable"
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add ${{ matrix.target }}
      - run: wget "https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q5_K_M.gguf" -O ./nobody/model.bin
      - run: cargo test -- --nocapture
        working-directory: ./nobody
