name: "Build and test"
on:
  pull_request:
  push:
permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      upload_artifacts: true

  test:
    uses: ./.github/workflows/test.yml
    needs: []

  release:
    needs: [build, test]
    uses: ./.github/workflows/release.yml
